### ISSUE TITLE
Update approval message

### ISSUE THREAD

**Issue by benjie** [somakeit/members-area#19]
- [ ] The wiki is integrated with the members area, so remove bracketed sentence
- [ ] Prompt them to set up GoCardless payments
- [ ] Change "approved by {Benjie Gillam}" to "approved by {number} trustees"
- [ ] Walk through setting up their wiki profile
- [ ] Link to webchat.freenode.net for IRC intro
- [ ] Link to our social accounts (twitter/etc)

**Comment by benjie** [comment]
@EdBrereton can I interest you in taking any of these tasks on? :)

**Comment by EdBrereton** [comment]
Can do. Will look at getting them sorted probably tomorrow/the weekend.

**Comment by benjie** [comment]
Awesome :)

**Comment by benjie** [comment]
Implemented perfectly in #22
