### ISSUE TITLE
Bug: profile update page

### ISSUE THREAD

**Issue by daverowntree** [somakeit/members-area#28]
Currently 'full name' gets populated to my email address, so when resetting my password, the code chokes with 'invalid full name'.  Repeating with my actual full name entered works, and the password is changed, but then the 'full name' field reverts back to my email address.

**Comment by benjie** [comment]
Nice find.

**Comment by benjie** [comment]
@daverowntree can you confirm this also occurs in other web browsers? I cannot reproduce and suspect it may be your autofill playing silly buggers.

**Comment by daverowntree** [comment]
Benjie,
you are right - it is my autofill playing up.  Works just fine with
chrome.  Guess I could have thought of that myself really...ah well.

Dave.

If in doubt - blame the software engineer...

**Comment by benjie** [comment]
Heh; no worries :)
