### ISSUE TITLE
Alternative signin methods

### ISSUE THREAD

**Issue by benjie** [somakeit/members-area#5]
Implement `everyauth` or similar to allow users to sign in with Facebook/Twitter/GitHub/etc instead of password.

**Comment by benjie** [comment]
Hey @bencevans, fancy taking this one on? http://everyauth.com/

**Comment by bencevans** [comment]
@benjie So long as your not in a rush as college deadlines approaching, sure! Have we got an internet connection down at rideride at all, maybe do on it on Friday if there's time

**Comment by benjie** [comment]
No rush - any time in the next 2 months (though sooner is better). Yes, we've got internet at So Make It :)

**Comment by bencevans** [comment]
@benjie This can be closed.
