### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by antonpiatek** [somakeit/members-area#6]
What do I need installed to actually run this code on a test system? and have you got any test data to start things off?
(are there any unit tests to run before commit?)

**Comment by bencevans** [comment]
You need:
- [node.js (+ npm)](https://nodejs.org)

Once you've installed node.js (npm is the package manager that comes with it), open up a terminal &...

``` bash
# Install coffeescript
[sudo] npm install -g coffee-script

# clone and enter directory
git clone git@github.com:so-make-it/members-area.git && cd members-area

# Install the members-area dependencies
npm install .

# Setup the database (this will create a SQLite DB at `./db.sqlite` and apply the table models)
SQLITE=1 coffee setup

# Start the server
SQLITE=1 SECRET=<INSERT_A_RANDOM_STRING> EMAIL_USERNAME=<GMAIL_EMAIL_ADDRESS> EMAIL_PASSWORD=<GMAIL_PASSWORD> APPROVAL_TEAM_EMAIL=<ANOTHER_OR_SAME_EMAIL_ADDRESS> coffee app

# Open your browser to http://localhost:1337 and you should have it running :)
```

There aren't any unit tests atm

//cc @antonpiatek

**Comment by antonpiatek** [comment]
awesome, thanks

**Comment by benjie** [comment]
I've taken @bencevans' instructions and stuck them into the README with some extra details. Using `.env` makes local dev much easier btw! :)

**Comment by benjie** [comment]
Also: unit tests would be welcome.

**Comment by antonpiatek** [comment]
I wouldn't even know where to begin writing unit tests for this... but if you start some off, I can probably pick it up...
